### ISSUE TITLE
Route not properly shown

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/modeify#179]
In this [example](http://www.carfreeatoz.com/planner?from=251%2018th%20St%20S%2C%20Arlington%2C%20Virginia%2022202&to=2100%20Clarendon%20Blvd%2C%20Arlington%2C%20Virginia%2C%20USA&modes=BICYCLE%2CBUS%2CTRAINISH%2CWALK%2CCAR&start_time=7&end_time=9&days=M%E2%80%94F) the blue line should only go through Rosslyn, while the yellow line should not.

![screenshot 2015-02-06 11 22 13](https://cloud.githubusercontent.com/assets/776780/6082888/883ba39e-adf2-11e4-9636-285ee02e6fac.png)

**Comment by trevorgerhardt** [comment]
The yellow and blue should split at the pentagon with the Yellow going to L'Enfant and ending. Since Blue overlaps with orange/silver it's correct.

**Comment by trevorgerhardt** [comment]
@demory ever take a look at this one?

**Comment by demory** [comment]
I looked at this today. Looping in @abyrd since I think this may need to be addressed on the OTP side.

The issue here is that the profile router is returning an option that includes Blue/Yellow from Crystal City to L'Enfant Plaza as a single combined segment (see [raw response](http://www.carfreeatoz.com/api/otp/profile?accessModes=WALK&bikeSpeed=4.1&date=2015-02-18&directModes=CAR%2CWALK&egressModes=WALK&endTime=9%3A00&from=38.8576374697945%2C-77.05090966035175&startTime=7%3A00&to=38.890519188410906%2C-77.08618819452875&limit=3&transitModes=TRAINISH&walkSpeed=1.4)). While it is technically true that both lines make this connection, the routes are entirely different, and in this case I imagine it will always make more sense to use Yellow.

I remember discussing this issue of when to merge multiple patterns that serve a given origin/destination pair, and as I recall we decided to merge patterns even when they have different intermediate stop sequences. The thinking being that you often have slightly different variants of (for example) a bus route serving a major corridor, with different patterns serving different sequences of stops along that corridor. And while I think it makes sense to merge in that case, in this Blue/Yellow example I think we should return two separate options.

It seems to me that we need some sort of logic that determines whether two given segments serve roughly the same alignment based on their stop sequences. I could conceivably add this on the Transitive side to detect and render this case correctly (currently Transitive assumes that any pattern in a patternsGroup list is representative of the group, alignment-wise -- hence the rendering of Yellow along Blue's alignment). But to me it makes more sense to do this on the OTP side, returning different options. @abyrd / @trevorgerhardt do you agree?

**Comment by demory** [comment]
Also looping in @mattwigway since I know you've been thinking about the issue of pattern identification / classification. Perhaps the alignment-comparison logic mentioned above should be part of the new com.conveyal.gtfs library?

**Comment by mattwigway** [comment]
Yep, basically what we need to do is implement some sort of edit-distance metric I think. Since short-turns are common, we probably only want to look at the edit distance for the stops in between the arrival and departure stops here.

**Comment by demory** [comment]
@mattwigway I'm familiar with edit-distance in the context of string comparison but how would it work in a geospatial context?

As I see it, what we need is a function that takes two sequences of lat/lon coordinates and determines if they follow roughly the same alignment (within some tolerance I suppose).

Say you have a sequence of stops [A,B,C,D,E,F] along a corridor and two patterns serving them, [A,B,D,F] and [A,C,E,F]. We want the alignment-comparison function to return "true" in this case. And say you have another pattern connecting A and F by a completely different alignment, [A,X,Y,F], which compared with either of the other two obviously should return false. Wouldn't edit-distance find all of these sequences to be equally dissimilar?

**Comment by mattwigway** [comment]
That is true, that is a failing of edit distance. In that case you probably want to buffer the line segments between the stops on pattern A and then see if pattern B falls within that buffer.

**Comment by mattwigway** [comment]
Or if some percentage of B falls within that buffer.

**Comment by abyrd** [comment]
There are two different views of what it means to combine routes here. One is visual and route-alignment oriented: the two trains take quite different paths and only share endpoints. The other is rider decision tree oriented: at a particular place in the trip, the rider can choose between two options to reach the same destination or downstream transfer point.

Both of these are valid, and I wouldn't want to privilege one at the expense of the other. Perhaps in this case the yellow line is so much worse that it should be left out of the result entirely; that is one problem. But if it is included, from the decision tree perspective it should arguably be combined with the blue line even if they have completely different alignments, especially if they happened to offer comparable travel times and the rider could choose on the fly, taking the first one that arrives at the platform.

They do appear as separate patterns in the response, so what prevents rendering them with different alignments despite being a combined segment? In fact I think it would be pretty cool to highlight an option or a leg of an option and see paths that diverge and re-converge on all the decision points.

**Comment by trevorgerhardt** [comment]
@demory & @abyrd where'd we leave off on this one?
