### ISSUE TITLE
Turn on Safest Bike Routes by Default

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/modeify#196]
Our most common complaint is the bicycle results are unreasonable. The roads are unsafe to ride on or the time shown is faster than possible. 

I've seen the *speed* vs *safety* vs *elevation* metric, but I'd rather not add that control to the UI. I suggest we change the default weights to emphasize the safest route, and possibly the flattest. 

Thoughts? @demory @abyrd

**Comment by abyrd** [comment]
Yeah we could just hard-wire them to different values. It would be straightforward to change those in the OTP code.

**Comment by trevorgerhardt** [comment]
Great! is that something we can do in the new config files?

**Comment by abyrd** [comment]
Yes, you should be able to specify triangleSafetyFactor, triangleSlopeFactor, and triangleTimeFactor in the default routing parameters. However in order for these to take effect, we also need to specify query parameter optimize=TRIANGLE. I don't actually know what will happen if we specify that in the config defaults, since it's only intended to apply to bicycles.

Really we should get rid of "optimize". It's a holdover from a very early stage of OTP development. The triangle factors should always apply when biking.

**Comment by abyrd** [comment]
I took a quick look, there's no chance of eliminating the optimize parameter for now, it's too entwined in the rest of the code. I also realized that the routing query parameter defaults specified in the router config JSON do not affect profile routing at all for the moment. Are you adjusting any of them? It would be pretty easy to make sure those settings get through to the profile router.

I also see in re-examining the street traversal code that optimize=TRIANGLE, indeed optimize=<anything> only has any effect when bicycling (at least in the code I've reviewed so far). If this is the case it seriously needs to be documented, since I never completely realized this.

**Comment by trevorgerhardt** [comment]
I am not currently using any of them. Ok so right now there need to be code changes to enable the triangle factors for profile routing.

If you point me in the right direction I could look at this.

**Comment by abyrd** [comment]
Yes but it's quite simple. I will try to get it in before the release.

**Comment by abyrd** [comment]
Unless we intend to set the other parameters (safe/flat/fast) we could also just choose optimize type SAFE. Let me know if there's any need to tweak the relative importance of these parameters or 1000% safe does what we need.
