### ISSUE TITLE
Bus labels not reflecting route colors

### ISSUE THREAD

**Issue by kchanba** [conveyal/modeify#281]
Using the Tyson's corner screenshot, the labels are blue where they should be yellow
![screen shot 2015-07-21 at 5 12 08 pm](https://cloud.githubusercontent.com/assets/2378745/8812861/b4955802-2fcc-11e5-9604-6e4ddd2ceae2.png)

**Comment by trevorgerhardt** [comment]
I'm not sure if we want the map labels to reflect the same color. They're fixed in the right panel, but are in multiple locations on the map and could be harder to see/find.

It would be interesting to see a side by side comparison of a few different colors and routes if you'd like to take a pass at that.

**Comment by kchanba** [comment]
Sure, I can do that. It would be best if the side panel labels matched those on the map and if they had a similarity to the branding of the provider. Of course there are limits to legibility on the map.
