### ISSUE TITLE
Walking directions inaccurate

### ISSUE THREAD

**Issue by kchanba** [conveyal/modeify#300]
'The left on the service road is unnecessary, the entrance to the metro is right on Cedar St NW in Takoma. You can end the walking directions to the metro at this point. The Carrol St NW and Service Rd portion is inaccurate."

[See route] (http://carfreeatoz.com/planner?from=7425%20Blair%20Rd%20NW%2C%20Washington%2C%20District%20of%20Columbia&to=810%201st%20St%20NE%2C%20Washington%2C%20District%20of%20Columbia&modes=BICYCLE%2CBICYCLE_RENT%2CBUS%2CTRAINISH%2CWALK%2CCAR&start_time=7&end_time=9&days=M%E2%80%94F)

**Comment by trevorgerhardt** [comment]
@kpwebb @abyrd OSM linkage to GTFS stops have been a noticeable issue for awhile now. Can we spend a bit of time brainstorming how this could be fixed, especially in a well known area for us like DC?

**Comment by trevorgerhardt** [comment]
1+ minute longer on either side can change the overall results.

**Comment by abyrd** [comment]
@trevorgerhardt there have been ongoing algorithmic problems with stop-to-street linking which mostly had to do with which types of ways are prioritized (car vs. pedestrian, platforms etc.) I think we've got a good handle on those. The real problem here appears to just be data quality. If you zoom all the way in to the Tacoma Metro station, you can see that OTP has simply connected it to the closest road. To ensure a perfect route, we'd need to:

A) Make sure the station platforms are tagged as such
B) Make sure there's a pedestrian walkway from the platforms to the true entrance on the main street
C) Move the GFTS stop to coincide with the OSM stop.

**Comment by trevorgerhardt** [comment]
@abyrd thanks! That's exactly what I'm getting at. What modifications need to occur to ensure appropriate linkage. Station platforms are an OSM object type that we check for? Is it appropriate to just create direct pathways from roads where known connections exist? https://www.openstreetmap.org/edit#map=18/38.97528/-77.01739

The coordinates of the GTFS stop there do look a bit off (could be us also?).
<img width="986" alt="screenshot 2015-07-30 09 47 22" src="https://cloud.githubusercontent.com/assets/776780/8984538/2b47f76e-36a0-11e5-82df-fcb92d6e3041.png">

**Comment by abyrd** [comment]
Yes, we want to make sure station platforms are in OSM and tagged as railway=platform or public_transit=platform. That will cause the transit stop to preferentially snap to the platforms instead of nearby streets. Then there just needs to be a pedestrian traversable path leading from the platform out to the roads (where the station entrance is).

**Comment by abyrd** [comment]
And yes, we should move the GTFS stop to coincide with the station in OSM if that's in our power. If not, tagging the platform should still solve the problem.

**Comment by trevorgerhardt** [comment]
Updated the sidewalks nearby to connect: https://www.openstreetmap.org/changeset/33287440

Will check this on next graph rebuild.

**Comment by trevorgerhardt** [comment]
The linkage is correct now
